### ISSUE TITLE
Crash onRestart() if SimpleRangeView XML has id attribute.

### ISSUE THREAD

**Issue by thebradness** [bendikv/simple-range-view#10]
Hello! Thank you so much for making this. It's an excellent utility.
I did find a problem: If the simple range view xml element has an id attribute, it will crash once Android restarts the app. I created a simple test application to test this but you can reproduce it with the demo app. 

1. Start the SimpleRangeView demo app.
2. Open a bunch of other apps.
3. Go back to the demo app.

If I open up enough applications to force Android to restart the demo app, the screen will go black for a second (when I return to the demo app) and I will get a crash dialog.

Of course, the "real life" scenario is that I'll open the app I'm working on, do some other things and then go back to my app an hour later and get a crash. The above is just an easy way to reproduce the issue.

**Comment by bendikv** [comment]
Thank you for the feedback!
Fixed in 0.2.0
