### ISSUE TITLE
Thumb movements

### ISSUE THREAD

**Issue by denebchorny** [bendikv/simple-range-view#2]
Hi,
I was trying to implement your library and there was an issue. if I select minDistance as 0 then I can't be able to move THUMBS if one is over the other. 

What do I recommend?

I recommend let the Thumbs move freely. It doesn't matter if one is start thumb or end thumbs. You can handle the logic when a thumb changes from being start to end. I don't know if I am understandable. English is not my native language.

**Comment by bendikv** [comment]
Hi
Could you give me an example where you need to minDistance was equal to 0?

**Comment by denebchorny** [comment]
Yes, why not?

I'll show you 2 examples:

1) The first one is when I need minDistance as 0 because

When the user can choose a value between 1 and 8 and inclusive can only indicate a value. That is, you can choose from 1 to 3, or 2 to 5, as you could choose from 1 to 1 because he is simply interested in that value.

Example of my simple-range
```java
<me.bendik.simplerangeview.SimpleRangeView
                android:id="@+id/pointsRange"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginEnd="@dimen/spacing_lg"
                android:layout_marginLeft="@dimen/spacing_lg"
                android:layout_marginRight="@dimen/spacing_lg"
                android:layout_marginStart="@dimen/spacing_lg"
                android:layout_marginTop="@dimen/spacing_md"
                app:activeLineColor="@color/greenText"
                app:activeLineThickness="2dp"
                app:activeThumbColor="@color/greenText"
                app:activeThumbRadius="12dp"
                app:activeTickColor="@color/greenText"
                app:count="8"
                app:end="8"
                app:lineColor="@color/grayRangeLine"
                app:lineThickness="2dp"
                app:minDistance="0"
                app:showActiveTicks="false"
                app:showFixedTicks="false"
                app:showLabels="false"
                app:showTicks="false"
                app:start="0"
                app:tickColor="@color/greenText" />
```

2) The second one is when minDistance is mora than 0. It could be high but anyway the problem indicated exists. How is possible?

See this example:

```java
<me.bendik.simplerangeview.SimpleRangeView
                android:id="@+id/priceRange"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginEnd="@dimen/spacing_lg"
                android:layout_marginLeft="@dimen/spacing_lg"
                android:layout_marginRight="@dimen/spacing_lg"
                android:layout_marginStart="@dimen/spacing_lg"
                android:layout_marginTop="@dimen/spacing_md"
                app:activeLineColor="@color/greenText"
                app:activeLineThickness="2dp"
                app:activeThumbColor="@color/greenText"
                app:activeThumbRadius="12dp"
                app:count="1000"
                app:end="1000"
                app:lineColor="@color/grayRangeLine"
                app:lineThickness="2dp"
                app:minDistance="10"
                app:showActiveTicks="false"
                app:showFixedTicks="false"
                app:showLabels="false"
                app:showTicks="false"
                app:start="0"
                app:tickColor="@color/greenText" />
```

In this case the COUNT is too big then the minDistance causes the same problem as if it were zero because of its proximity between the two thumbs.

Tell me if I am right or if you need something else don't hesitate to ask me

**Comment by bendikv** [comment]
Ok. I understand what you mean. I will implement this feature soon.
Thank you for your contribution to the development of this library.

**Comment by denebchorny** [comment]
Don't worry, it is just an Idea. At this moment I am very bussy. But later I could help you to add features if you don't have any problem :D
