### ISSUE TITLE
Set max distance / disable range adjustments

### ISSUE THREAD

**Issue by Querschlag** [bendikv/simple-range-view#3]
First of all, this is a great library and I like to see that Kotlin is getting some love here ;)
I have a few questions:
1. Is there a way to set a maximum distance for the range selector, so the user could move the range but never adjust over a certain value?
2. Is it possible to disable range adjustments while still allowing to move the range?

**Comment by bendikv** [comment]
Hello, @Querschlag! Thank you for using the library. Your suggestions look good for me. I'll implement both suggestions in the next release of the library.

**Comment by bendikv** [comment]
Hello, @Querschlag! 
Both your suggestions were released in 0.2.0. Thank you!
